HYMN/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from HYMN import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('hymns/', include('hymns.urls')),
    path('sumu/', include('sumu.urls')),
    path('nyimbo/', include('nyimbo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hymns/urls.py
from django.urls import path

from . import views

app_name = 'hymns'

urlpatterns = [
    path('', views.index, name='home'),
    path('<int:header_id>/', views.details, name='details'),
    path('search/', views.search, name='search'),
    # path('sumu/', views.sumu, name='sumu'),
    # path('nyimbo/', views.nyimbo, name='nyimbo'),
]

nyimbo/urls.py
from django.urls import path

from nyimbo import views

app_name = 'nyimbo'

urlpatterns = [
    path('', views.index, name='home'),
    path('funsa/', views.funsa, name='funsa'),
    # path('search/', views.search, name='search'),
    # path('sumu/', views.sumu, name='sumu'),
    # path('nyimbo/', views.nyimbo, name='nyimbo'),
]

sumu/urls.py
from django.urls import path

from . import views

app_name = 'sumu'

urlpatterns = [
    path('', views.index, name='home'),
    path('fumba/', views.fumba, name='fumba'),
    # path('search/', views.search, name='search'),
    # path('sumu/', views.sumu, name='sumu'),
    # path('nyimbo/', views.nyimbo, name='nyimbo'),
]

hymns/models.py
from django.db import models


class Header(models.Model):
    header_text = models.CharField(max_length=255)

    def __str__(self):
        return self.header_text


class Title(models.Model):
    header_id = models.ForeignKey(Header, on_delete=models.CASCADE)
    hymn_number = models.IntegerField(default=0)
    hymn_title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.hymn_title


class Stanza(models.Model):
    header_id = models.ForeignKey(Header, on_delete=models.CASCADE, default='')
    title_id = models.ForeignKey(Title, on_delete=models.CASCADE)
    stanza_number = models.IntegerField(default=0)
    stanza_text = models.TextField()

    def __str__(self):
        return self.stanza_text

nyimbo/models.py
from django.db import models


class MutuNyimbo(models.Model):
    mutu_wa_nyimbo = models.CharField(max_length=255)

    def __str__(self):
        return self.mutu_wa_nyimbo


class Dzina(models.Model):
    mutu_nyimbo_id = models.ForeignKey(MutuNyimbo, on_delete=models.CASCADE)
    nambara_ya_nyimbo = models.IntegerField(default=0)
    dzina_la_nyimbo = models.CharField(max_length=255)
    olemba = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.dzina_la_nyimbo


class Ndime(models.Model):
    mutu_nyimbo_id = models.ForeignKey(MutuNyimbo, on_delete=models.CASCADE, default='')
    dzina_id = models.ForeignKey(Dzina, on_delete=models.CASCADE)
    nambara = models.IntegerField(default=0)
    ndime = models.TextField()

    def __str__(self):
        return self.ndime

sumu/models.py
from django.db import models


class MutuSumu(models.Model):
    mutu_wa_sumu = models.CharField(max_length=255)

    def __str__(self):
        return self.mutu_wa_sumu


class Zina(models.Model):
    mutu_sumu_id = models.ForeignKey(MutuSumu, on_delete=models.CASCADE)
    nambala_ya_sumu = models.IntegerField(default=0)
    zina_la_sumu = models.CharField(max_length=255)
    mlembi = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.zina_la_sumu


class Mizere(models.Model):
    mutu_sumu_id = models.ForeignKey(MutuSumu, on_delete=models.CASCADE, default='')
    zina_id = models.ForeignKey(Zina, on_delete=models.CASCADE)
    nambala = models.IntegerField(default=0)
    mizere = models.TextField()

    def __str__(self):
        return self.mizere

HYMN/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home.html', {'brand_name': "HYMNS OF MALAWI", 'brand_url': "/", })  # 'bg_color': "bg-home"})

hymns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import (
    Header, Title, Stanza,
    #MutuSumu, Zina,
    #MutuNyimbo, Dzina
)

def index(request):
    hymns = Header.objects.all
    return render(request, 'hymns/index.html', {'hymns': hymns, 'bg_color': "bg-primary", 'brand_name': "HYMNS", 'brand_url': "/hymns/"})

def create(request):
    pass

def search(request):
    #try:
    search_text = request.POST['search']
    #if search_text != '':
        #hymn = get_object_or_404(Title, hymn_number=search_text)
        #return render(request, 'hymns/details.html', {'hymn': hymn})
    #except Title.DoesNotExists:
    if search_text != '': #or error:
        try:
            hymn_s = Title.objects.get(hymn_number=search_text)
        except Title.DoesNotExist:
            hymn_s = ""
        # try:
        #     sumu = Zina.objects.get(nambala_ya_sumu=search_text)
        # except Zina.DoesNotExist:
        #     sumu = ""
        # try:
        #     nyimbo = Dzina.objects.get(nambara_ya_nyimbo=search_text)
        # except Dzina.DoesNotExist:
        #     nyimbo = ""
        # Need to check individual variables if they are empty if not send them to template  'sumu': sumu, 'nyimbo': nyimbo,
        return render(request, 'hymns/details.html', {'hymn_s': hymn_s,  'bg_color': "bg-primary", 'brand_name': "HYMNS", 'brand_url': "/hymns/"})
    else:
        return render(request, 'hymns/details.html', {'error': "Please enter a number or text", 'bg_color': "bg-primary", 'brand_name': "HYMNS", 'brand_url': "/hymns/"})
        #return redirect(reverse('hymns:home'))

# def sumu(request):
#     sumu = MutuSumu.objects.all
#     return render(request, '/sumu/templates/sumu/index.html', {'sumu': sumu})
#
# def nyimbo(request):
#     nyimbo = MutuNyimbo.objects.all
#     return render(request, '/nyimbo/templates/nyimbo/index.html', {'nyimbo': nyimbo})

def details(request, header_id):
    hymn = get_object_or_404(Header, pk=header_id)
    return render(request, 'hymns/details.html', {'hymn': hymn})

nyimbo/views.py
from django.shortcuts import render

from nyimbo.models import MutuNyimbo, Dzina


def index(request):
    nyimbo = MutuNyimbo.objects.all
    return render(request, 'nyimbo/index.html', {'nyimbo': nyimbo, 'bg_color': "bg-info", 'brand_name': "NYIMBO ZA MULUNGU", 'brand_url': "/nyimbo/"})


def funsa(request):
    try:
        funso = request.POST['funso']
        if funso != '':
            nyimbo = Dzina.objects.get(nambara_ya_nyimbo=funso)
            return render(request, 'nyimbo/result.html', {'nyimbo': nyimbo, 'bg_color': "bg-info", 'brand_name': "NYIMBO ZA MULUNGU", 'brand_url': "/nyimbo/"})
    except Dzina.DoesNotExist:
        return render(request, 'nyimbo/result.html', {'vuto': "NYIMBO " + funso + " MULIBE", 'bg_color': "bg-info", 'brand_name': "NYIMBO ZA MULUNGU", 'brand_url': "/nyimbo/"})

sumu/views.py
from django.shortcuts import render

from sumu.models import MutuSumu, Zina


def index(request):
    sumu = MutuSumu.objects.all
    return render(request, 'sumu/index.html', {'sumu': sumu, 'bg_color': "bg-success", 'brand_name': "SUMU ZA UKHRISTU", 'brand_url': "/sumu/"})


def fumba(request):
    try:
        fumbo = request.POST['fumbo']
        if fumbo != '':
            sumu = Zina.objects.get(nambala_ya_sumu=fumbo)
            return render(request, 'sumu/result.html', {'sumu': sumu, 'bg_color': "bg-success", 'brand_name': "SUMU ZA UKHRISTU", 'brand_url': "/sumu/"})
    except Zina.DoesNotExist:
        return render(request, 'sumu/result.html', {'suzgo': "SUMU " + fumbo + " MULIJE PANYAKE MULIVE", 'bg_color': "bg-success", 'brand_name': "SUMU ZA UKHRISTU", 'brand_url': "/sumu/"})

hymns/templates/hymns/details.html
{% extends 'base.html' %}

{% block content %}
    {% if hymn %}
    <h2 class="mb-5 text-center">{{ hymn.header_id.header_text }}</h2>
    
    <ul class="list-group mb-5">
        {# {% for title in hymn.title_set.all %} #}
        <li class="list-group-item">
            <h4>{{ hymn.hymn_number}}. {{ hymn.hymn_title }}</h4> {# <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span> #}
            <ol>
                {% for stanza in hymn.stanza_set.all %}
                <li><p class="lead m-5 p-5">{{stanza.stanza_text}}</p></li>
                {% endfor %}
            </ol>
        </li>
        {# {% endfor %} #}
    </ul>
    {% elif hymn_s or sumu or nyimbo %}
    <h2 class="mb-5 text-center">{{ hymn_s.hymns.header_text }}</h2>
    <!-- English -->
    <ul class="list-group mb-5">
        {# {% for title in hymn_s.title_set.all %} #}
        <li class="list-group-item">
            <h4>{{ hymn_s.hymn_number}}. {{ hymn_s.hymn_title }}</h4>
            <ol>
                {% for stanza in hymn_s.stanza_set.all %}
                <li><p class="lead">{{stanza.stanza_text}}</p></li>
                {% endfor %}
            </ol>
        </li>
        {# {% endfor %} #}
    </ul>
    <!-- Tumbuka -->
    <h2 class="mb-5 text-center">{{ sumu.mutusumu.mutu_wa_sumu }}</h2>
    
    <ul class="list-group mb-5">
        {# {% for zina in sumu.zina_set.all %} #}
        <li class="list-group-item">
            <h4>{{ sumu.nambala_ya_sumu}}. {{ sumu.zina_la_sumu }}</h4>
            <ol>
                {% for mizere in sumu.mizere_set.all %}
                <li><p class="lead">{{mizere.mizere}}</p></li>
                {% endfor %}
            </ol>
        </li>
        {# {% endfor %} #}
    </ul>
    <!-- Chewa -->
    <h2 class="mb-5 text-center">{{ nyimbo.hymns.header_text }}</h2>
    
    <ul class="list-group mb-5">
        {# {% for dzina in nyimbo.dzina_set.all %} #}
        <li class="list-group-item">
            <h4>{{ nyimbo.nambara_ya_nyimbo}}. {{ nyimbo.dzina_la_nyimbo }}</h4> {# <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span> #}
            <ol>
                {% for ndime in nyimbo.ndime_set.all %}
                <li><p class="lead">{{ndime.ndime}}</p></li>
                {% endfor %}
            </ol>
        </li>
        {# {% endfor %} #}
    </ul>
    {% else %}
    <div class="list-group">
        <h4 class="list-group-item">No Result</h4>
    </div>
    {% endif %}
    {% if error %}
        <div class="alert alert-danger alert-dismissable">
            <p class="alert-text">{{error}}</p>
        </div>
    {% endif %}
{% endblock %}

hymns/templates/hymns/index.html
{% extends 'base.html' %}

{% block navlinks %}
    <a href="{% url 'sumu:home' %}" class="nav-item nav-link">TUMBUKA</a>
    <a href="{% url 'nyimbo:home' %}" class="nav-link">CHEWA</a>
{% endblock %}

{% block content %}
    {% for hymn in hymns %}
    {% include 'partials/_search.html' %}
    <h2 class="mb-5 text-center">{{ hymn.header_text }}</h2>
    
    <ul class="list-group mb-5">
        {% for title in hymn.title_set.all %}
        <li class="list-group-item">
            <h4>{{ title.hymn_number}}. {{ title.hymn_title }}</h4>
            {# <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span> #}
            <ol>
                {% for stanza in title.stanza_set.all %}
                <li><p class="lead mr-5 pr-5" style="width: 200px;">{{stanza.stanza_text}}</p></li>
                {% endfor %}
            </ol>
        </li>
        {% endfor %}
    </ul>

    {% endfor %}
{% endblock %}

{% block footer %}

{% endblock %}

hymns/templates/partials/_search.html
<form class="input-group mt-2 mb-2" method="post" action="{% url 'hymns:search' %}">
    {% csrf_token %} 
    <input class="form-control" type="search" name="search" id="search"> 
    <button class="btn btn-primary" type="submit">Search</button>
</form>

hymns/templates/partials/_search_global.html
<div class="input-group mt-2 mb-2">
    {% csrf_token %} 
    <input class="form-control" type="search" name="search" id="search"> 
    <button class="btn btn-primary" type="submit">Search</button>
</div>

nyimbo/templates/nyimbo/_funsa.html
<form action="{% url 'nyimbo:funsa' %}" method="POST">
    <div class="input-group mt-2 mb-2">
        {% csrf_token %}
        <input class="form-control" type="search" name="funso" id="funso">
        <button class="btn btn-info" type="submit">Search</button>
    </div>
</form>

nyimbo/templates/nyimbo/index.html
{% extends 'base.html' %}

{% block navlinks %}
    <a href="{% url 'sumu:home' %}" class="nav-link nav-item">Tumbuka</a>
    <a href="{% url 'hymns:home'%}" class="nav-link nav-item">English</a>
{% endblock %}

{% block content %}
    {% include 'nyimbo/_funsa.html' %}
    {% if nyimbo %}
    {% for nyimbo in nyimbo %}
        <h2 class="mb-5 text-center">{{ nyimbo.mutu_wa_nyimbo }}</h2>

        <ul class="list-group mb-5">
            {% for dzina in nyimbo.dzina_set.all %}
            <li class="list-group-item">
                <h4>{{ dzina.nambara_ya_nyimbo}}. {{ dzina.dzina_la_nyimbo }}</h4>
                <ol>
                    {% for ndime in dzina.ndime_set.all %}
                    <li><p class="lead">{{ndime.ndime}}</p></li>
                    {% endfor %}
                </ol>
            </li>
            {% endfor %}
        </ul>
    {% endfor %}
    {% endif %}
{% endblock %}

nyimbo/templates/nyimbo/result.html
{% extends 'base.html' %}

{% block navlinks %}
    <a href="{% url 'sumu:home' %}" class="nav-link nav-item">Tumbuka</a>
    <a href="{% url 'hymns:home'%}" class="nav-link nav-item">English</a>
{% endblock %}

{% block content %}
    {% include 'nyimbo/_funsa.html' %}
    {% if vuto %}
        <h3 class="mb-5 text-center">{{ vuto }}</h3>
    {% else %}
    <h2 class="mb-5 text-center">{{ nyimbo.mutu_nyimbo_id.mutu_wa_nyimbo }}</h2>

    <ul class="list-group mb-5">
        <li class="list-group-item">
            <h4>{{ nyimbo.nambara_ya_nyimbo}}. {{ nyimbo.dzina_la_nyimbo }}</h4>
            <ol>
                {% for ndime in nyimbo.ndime_set.all %}
                <li><p class="lead">{{ndime.ndime}}</p></li>
                {% endfor %}
            </ol>
        </li>
    </ul>
    {% endif %}
{% endblock %}

sumu/templates/sumu/_fumba.html
<form action="{% url 'sumu:fumba' %}" method="POST">
    <div class="input-group mt-2 mb-2">
        {% csrf_token %}
        <input class="form-control" type="search" name="fumbo" id="fumbo" required/>
        <button class="btn btn-success" type="submit">Search</button>
    </div>
</form>

sumu/templates/sumu/index.html
{% extends 'base.html' %}

{% block navlinks %}
    <a href="{% url 'nyimbo:home' %}" class="nav-item nav-link">Chewa</a>
    <a href="{% url 'hymns:home' %}" class="nav-item nav-link">English</a>
{% endblock %}

{% block content %}
    {% include 'sumu/_fumba.html' %}
    {% if sumu %}
        {% for sumu in sumu %}
            <h2 class="mb-5 text-center">{{ sumu.mutu_wa_sumu }}</h2>

            <ul class="list-group mb-5">
                {% for zina in sumu.zina_set.all %}
                <li class="list-group-item">
                    <h4>{{ zina.nambala_ya_sumu}}. {{ zina.zina_la_sumu }}</h4>
                    <ol>
                        {% for mizere in zina.mizere_set.all %}
                        <li><p class="lead">{{mizere.mizere}}</p></li>
                        {% endfor %}
                    </ol>
                </li>
                {% endfor %}
            </ul>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block footer %}
{% endblock %}

sumu/templates/sumu/result.html
{% extends 'base.html' %}

{% block navlinks %}
    <a href="{% url 'nyimbo:home' %}" class="nav-item nav-link">Chewa</a>
    <a href="{% url 'hymns:home' %}" class="nav-item nav-link">English</a>
{% endblock %}

{% block content %}
    {% include 'sumu/_fumba.html' %}
    {% if suzgo %}
        <h3 class="mb-5 text-center">{{ suzgo }}</h3>
    {% else %}
    <h2 class="mb-5 text-center">{{ sumu.mutu_sumu_id.mutu_wa_sumu }}</h2>

    <ul class="list-group mb-5">
        <li class="list-group-item">
            <h4>{{ sumu.nambala_ya_sumu}}. {{ sumu.zina_la_sumu }}</h4>
            <ol>
                {% for mizere in sumu.mizere_set.all %}
                <li><p class="lead">{{mizere.mizere}}</p></li>
                {% endfor %}
            </ol>
        </li>
    </ul>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link href="{% static 'images/ic_icon_round_white.png' %}" rel="icon" type="image/x-icon">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
  <script src="{% static 'font-awesome-6.2.0/js/all.min.js' %}" type="text/javascript"></script>
  <title>HYMN</title>
  <style>
      .bg-home {
          background: #4fddfb;
      }
  </style>
</head>
<body style="background: #59fff3;">
  <nav class="navbar navbar-expand navbar-dark {{ bg_color }}">
    <img src="{% static 'images/ic_icon_rounded_coner.png' %}" class="mr-3" height="50px !important" alt="logo"/>
    <a href="{{ brand_url }}" class="navbar-brand">{{ brand_name }}</a>
    <div class="navbar-nav ml-auto">
      {% block navlinks %}
      {% endblock %}
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <footer class="card-footer text-lg-center text-md-center text-white {{ bg_color }} fixed-bottom">
    &copy; Copyright JOYOUS B.W. CHIRWA Jr {% now 'Y' %}
    {% block footer %}
    {% endblock %}
  </footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block navlinks %}
    <a href="{% url 'hymns:home' %}" class="nav-link active">English Hymns</a>
    <a href="{% url 'sumu:home' %}" class="nav-link active">Tumbuka Hymns</a>
    <a href="{% url 'nyimbo:home' %}" class="nav-link active">Chichewa Hymns</a>
{% endblock %}

{% block content %}
    <figure class="text-center  pt-1">
        <img src="{% static 'images/ic_icon_coner.png' %}" class="img-fluid" />
        <figcaption class="lead">
            <p>HYMNS FOR MALAWI IN THREE LANGUAGES</p>
        </figcaption>
    </figure>

    <div class="row d-flex">
        <div class="col-4 d-flex text-center">
            <a href="{% url 'hymns:home' %}" class="btn btn-primary btn-lg mt-2 mb-3 ml-auto mr-auto">ENGLISH HYMN</a>
        </div>
        <div class="col-4 d-flex text-center">
            <a href="{% url 'sumu:home' %}" class="btn btn-success btn-lg mt-2 mb-3 ml-auto mr-auto">SUMU ZA UKHRISTU</a>
        </div>
        <div class="col-4 d-flex text-center">
            <a href="{% url 'nyimbo:home' %}" class="btn btn-info btn-lg mt-2 mb-3 ml-auto mr-auto">NYIMBO</a>
        </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="{% static 'css/tailwind.css'%}" rel="stylesheet" type="text/css" />
  <script src="{% static 'font-awesome-6.2.0/js/all.min.js' %}" type="text/javascript" ></script>
  <title>HYMN</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

</body>
</html>